### ISSUE TITLE
[Issue] Default Admin Set

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#27]
We currently are not using the Default Admin Set and have yet to explore what it means.  Apparently, it can be set up to control various workflows.  In the meantime, it creates confusion for users when adding a work to a collection.  Until we understand how to use the Default Admin Set, it might be best to remove it for the display.

**Comment by jkim-ru** [comment]
I'm going to remove references to the default admin set in the views that non-admin users can see.

**Comment by jkim-ru** [comment]
It turns out that Hyrax already has part of the solution configurable.  Administrators can go to Administration > Settings. From there, he or she can turn off the "Assign admin set" option.  This will remove the Admin set reference from the main homepage and the create/update forms. However, I'm still seeing this in the show view, so I'll look to modify that.
<img width="1197" alt="screen shot 2017-11-09 at 2 11 30 pm" src="https://user-images.githubusercontent.com/25179501/32624680-f02fa548-c557-11e7-8744-07c5106c27d8.png">

**Comment by jkim-ru** [comment]
I added a check to the "Flipflop" settings before displaying the Admin Set information.
