### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by anniekj** [dibbs-vdc/ccql#30]
Shouldn't profiles have the option to have a photo?

**Comment by jkim-ru** [comment]
Yes, in a vanilla Hyrax application, this is an option. However, we removed the ability for the user to update their profile because it's now tied into their Fedora Person object. I think we didn't want users to have free reign over their Person information. And so, with this removal, went the option to add/update photos. 

If we want to add this back in, we'll have to discuss what that's going to look like.

I think there was mention of eventually adding a workflow for updating Person/User info, but we're pretty off from that.

**Comment by anniekj** [comment]
Ok! Thanks.
