### ISSUE TITLE
Date Created

### ISSUE THREAD

**Issue by anniekj** [dibbs-vdc/ccql#32]
Date created field only appears in short description for work. It is not present when you actually look at the work's page.

Also: Can you provide a hint for how you would like date created to be entered? ie. 10-26-17, October 26, 2017, 26-10-17? Currently it allows you to enter the date in all different ways.

**Comment by jkim-ru** [comment]
I'm going to use this ticket to fix both the issue Annie brought up, and another related issue.

I am currently using the existing basic hyrax metadata:

```
date_created | ::RDF::Vocab::DC.created
```

However, I need to change this property to have our own predicate, so that it matches the current metadata spreadsheet:

```
creation_date | https://datacollaboratory.org/resource#creationDate
```

Hints were added in related issue #36.

**Comment by jkim-ru** [comment]
Added longer term fix in the feature/59/hyrax-2-migration branch. I plan to close the ticket once this branch gets merged back into master.

**Comment by jkim-ru** [comment]
NOTE: This issue is closed, but I added a simple rake task to move the data from date_created to creation_date.
