### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#44]
How are search results ordered?

**Comment by jkim-ru** [comment]
To some extent, you can choose the sort order by selecting from the drop down.

<img width="1161" alt="screen shot 2017-11-03 at 3 06 54 pm" src="https://user-images.githubusercontent.com/25179501/32391513-c2ad2162-c0a8-11e7-8ace-7a6508cf5461.png">

It looks like the default ordering is by "relevance". The relevance is based off of the ``score`` in the response from Solr when a query is made.  From the Solr Admin UI, all of the hits that I've seen so far have had a score of 1.0.

So, what happens when all the scores are equal? From what I see, it looks like Solr is returning them in the order that they were first uploaded. Modifying a work does not seem to change its placement in the search results when all of the scores are the same and the ordering is by relevance (as far as I can tell at least). I haven't found code yet to verify this, but I'll post back if I do find it (or if I give up).

One link that is helpful is the following:
https://github.com/projectblacklight/blacklight/wiki/Configuration---Solr-fields

It describes how to configure the types of sorting options in the drop down. For our application, they are currently defined here: https://github.com/dibbs-vdc/ccql/blob/e58400f74a22282cedb3f6be7767733b527d1517/app/controllers/catalog_controller.rb#L335

**Comment by jkim-ru** [comment]
I can't find any documentation that definitely describes what happens to the sort order when the scores are all the same. However, I did find information on how to configure multiple sort orderings, so we can change the ordering if need be.

https://wiki.apache.org/solr/CommonQueryParameters#sort

**Comment by jkim-ru** [comment]
Closing this for now. Please feel free to open it up again for any reason!
