### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#46]
How do I send a notification?

**Comment by jkim-ru** [comment]
What kind of notification?

**Comment by jkim-ru** [comment]
Looking at the code, it seems like notifications (in hyrax 1.0.4 and soon-to-be-released 2.0.0) are sent to the user by the application when there is a change or progress is made in the depositing workflow. Right now, we're testing with the default admin set's default workflow, which they describe as "a single submission step".  Since no mediation is required, there are no notifications sent out, so we're not seeing them.

For a vanilla Hyrax application, I don't think users can send other users a notification, though we might be able to use existing code to add functionality like that in the future.

I put a question in the slack channel asking if notifications are only related to workflows, and the one response (Bess Sadler) I got seems to confirm what I'm seeing. If we want to add user notifications programmatically in the future, we can.

From Bess in the slack channel: "I have some notifications that I wrote myself that get triggered when a cron job detects that an embargo will expire soon, for example"
